import Image from "next/image";
import Link from "next/link";
import styles from "./page.module.scss";

/**
 * Example Home Page
 * This is an example home page that is generated by the wi-next-starter kit.
 * It is a simple page that displays a welcome message and a button to login.
 * @returns The ExampleHomePage component
 */
export default function ExampleHomePage() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <Image
          src={"/images/placeholder.svg"}
          alt="placeholder"
          width={300}
          height={100}
          priority
        />
        <p>
          This is an example home page that is generated by the wi-next-starter
          kit.
        </p>
        <Link
          className={styles.cta}
          href="https://www.google.com"
          target="_blank"
        >
          Launch Google
        </Link>
      </main>
    </div>
  );
}
