import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "WorkIndia Next Starter Kit",
  description: "Generated by wi-next-starter",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}