import type { Metadata } from "next";
import { inter } from "./fonts";
import "./globals.css";
import { ContextWrapper } from "@/app/context-wrapper";
import { ThemeProvider } from "@/theme/ThemeProvider";

export const metadata: Metadata = {
  title: "Call Quality Analytics",
  description: "Generated by wi-next-starter",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <ContextWrapper>
            {children}
          </ContextWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}